apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-k8s
    app.kubernetes.io/managed-by: Helm
    release: jenkins
  name: service-public-jenkins
  annotations:
    meta.helm.sh/release-name: jenkins
    meta.helm.sh/release-namespace: ci
spec:
  type: LoadBalancer # <- Creates AWS Classic Load Balancer
  selector:
    app: jenkins-k8s
    release: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80