apiVersion: v1
kind: Service
metadata:
  namespace: ci
  labels:
    app: jenkins-k8s
    app.kubernetes.io/managed-by: Helm
    release: jenkins
  name: np-jenkins
  annotations:
    meta.helm.sh/release-name: jenkins
    meta.helm.sh/release-namespace: ci
spec:
  type: NodePort # <- Creates AWS Classic Load Balancer
  selector:
    app: jenkins-k8s
    release: jenkins
  ports: 
  - name: httpport
    port: 8080
  - name: jnlpport
    port: 50000